version: "3.7"

services:
  mysql-service:
    image: mysql:5.7
    networks:
      - antena-network
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_USER={MYSQL_USER}
      - MYSQL_PASSWORD={MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=AccountSystem

    restart: always
    
  web-service:
    image: mateusmsouza4/antenas-project
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME={MYSQL_USER}
      - DB_PASSWORD={MYSQL_ROOT_PASSWORD}
      - DB_HOST=jdbc:mysql://mysql-service:3306/AccountSystem?useTimezone=true&serverTimezone=UTC
    networks:
      - antena-network
    depends_on:
      - mysql-service

    restart: on-failure
      
networks:
  antena-network:
    driver: bridge
