version: "3.7"

services:
  mysql-service:
    image: mysql:5.7
    networks:
      - antena-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=AccountSystem

    restart: on-failure
    
  web-service:
    image: mateusmsouza4/antenas-project
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_HOST=jdbc:mysql://mysql-service:3306/AccountSystem?useTimezone=true&serverTimezone=UTC&useSSL=false
    networks:
      - antena-network
    depends_on:
      - mysql-service

    restart: on-failure
      
networks:
  antena-network:
    driver: bridge
